### ISSUE TITLE
Auto Formatter on save issue

### ISSUE THREAD

**Issue by PhasecoreX** [SpartanJ/ecode#10]
When enabling the `"auto_format_on_save": true` for the Auto Formatter plugin, the file will format correctly, however it will not be saved. Seems like the file is being saved, and then the formatter formats the code after, leaving the editor in a dirty state (little asterisk in the file tab at the top). You have to save again to actually commit those formattings to the disk, which still won't clear the dirty editor asterisk, as it will format again after saving (but, nothing changes, so it's weird that saving doesn't remove the asterisk).

I'm using python black as the formatter in this case.

**Comment by SpartanJ** [comment]
Hi! Thanks for reporting it! It makes sense it fails because black works differently than other formatters. I'll take a look.
