### ISSUE TITLE
Lack of IME support

### ISSUE THREAD

**Issue by xmokay** [SpartanJ/ecode#107]
Lacks support for the input method. Many input methods might require multiple key presses to input a single character, or a single key press to input multiple characters. There will be input prompts during the process. This is commonly seen in Chinese input methods.

**Comment by SpartanJ** [comment]
That's correct. I'm really unfamiliar on how IME works and never took the time to implement it. I understand this is a blocking issue for many people so I need to investigate it.

**Comment by SpartanJ** [comment]
IME support has been added in current eepp development branch. Next ecode's version will ship with IME support. This is gonna be probably this week.
