### ISSUE TITLE
Ruff (Python) linter ignores pyproject.toml

### ISSUE THREAD

**Issue by PhasecoreX** [SpartanJ/ecode#11]
I think this is caused by the default `linters.json` specifying the ruff python linter with `--ignore=E402`

I simply added this to my `linters.json`, removing the `-n --ignore=E402` from the default one, and it now seems to work just fine:
```json
    {
      "file_patterns": ["%.py$"],
      "warning_pattern": "[^:]:(%d+):(%d+):%s([^\n]+)",
      "command": "ruff $FILENAME"
    }
```
I wasn't sure if doing this replaces the entire linters list from the default `linters.json`, or only the python linter specifically?

Also, your documentation says that python uses pycodestyle, which it looks like it uses ruff now (good call!)

**Comment by SpartanJ** [comment]
You are right. ecode shouldn't overwrite the `pyproject.toml` config. Your fix is perfectly fine, I'll change the default command used just as you did.

> I wasn't sure if doing this replaces the entire linters list from the default linters.json, or only the python linter specifically?

Overwrites the python linter specifically. The idea is to be able to overwrite and expand the base features.

Thanks for reporting it!

**Comment by SpartanJ** [comment]
Fixed [here](https://github.com/SpartanJ/eepp/commit/319d20aa5d03da416af13aa1ee347c0d711e41ec).
