### ISSUE TITLE
Unable to launch ecode on MacOS 13.6.1

### ISSUE THREAD

**Issue by monocodezz** [SpartanJ/ecode#110]
ecode version: 0.5.0

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
Referenced from: <8AC7A819-4B5E-3459-80E0-DEE3DD54FE5B> /Applications/ecode.app/Contents/MacOS/libeepp.dylib
Reason: tried: '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file)
(terminated at launch; ignore backtrace)
````

A temporary workaround is to add symlink in `/usr/local/lib` to bundled `libSDL2-2.0.0.dylib`

```
libSDL2-2.0.0.dylib -> /Applications/ecode.app/Contents/MacOS/libSDL2-2.0.0.dylib
```

**Comment by SpartanJ** [comment]
Oh :hankey: , I should have tested better some changes I made for the packaging of the x86_64 build. I'll upload a fixed build ASAP. Thanks for reporting it.

**Comment by monocodezz** [comment]
Understood. BTW, I'm using arm64 build.

**Comment by SpartanJ** [comment]
You're right! I didn't notice because I have the dependency locally.

**Comment by SpartanJ** [comment]
Re-released macOS arm64 dmg here: https://github.com/SpartanJ/ecode/releases/download/ecode-0.5.0/ecode-macos-0.5.0-arm64.dmg, please redownload and thank you again!

**Comment by monocodezz** [comment]
I can confirm the fix with a new build. Thank you for your hard work!
