### ISSUE TITLE
Portable/usb stick mode?

### ISSUE THREAD

**Issue by thequver** [SpartanJ/ecode#113]
Consider adding portable/usb stick mode to ecode. Currently (on Windows) it creates a folder in C:/Users/USER/AppData/Roaming/ecode, would be good if there was an option so the program stores everything it needs in the same folder as the main exe file

**Comment by SpartanJ** [comment]
Hi! Yes, it should be pretty easy with a command line flag, but I don't want to maintain two different packages because it adds more work to the releases. So what we can do is add a command line option `ecode.exe --portable` and add a shortcut access for the portable version.

**Comment by thequver** [comment]
Also some apps do it by checking if there is a file named portable near the exe so this is another way of doing it

**Comment by SpartanJ** [comment]
Can you give me a precise example or app example so I can see if it's worth copying that method? Thank

**Comment by thequver** [comment]
This 2 i'm aware of:
OBS studio https://github.com/obsproject/obs-studio
https://obsproject.com/forum/resources/obs-and-obs-studio-portable-mode-on-windows.359/

Chainner https://github.com/chaiNNer-org/chaiNNer

**Comment by SpartanJ** [comment]
Added support for portable mode, it will be part of the next release (0.5.1), changes [here](https://github.com/SpartanJ/eepp/commit/ece5de2a1b55f056020b6c2fea7a2397e2cac82c).
It can be invoked the same way than obs-studio:
by command line argument with `--portable` or `-p` and by creating a file besides the `ecode` binary called `portable_mode.txt`.
