### ISSUE TITLE
Alt-tabbing on windows causes selected text to be deleted

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#115]
Video:

https://github.com/SpartanJ/ecode/assets/48155462/b7291f88-3771-4d17-a1c2-10a8caab089e

**Comment by SpartanJ** [comment]
Thanks. That's annoying, i'll have to test it on Windows, it does not happen in the other OSes, but Windows is by far the least tested OS since I don't personally use Windows.

**Comment by SpartanJ** [comment]
Fix was introduced in the latest version due to some changes for proper IME support, there seems to be a bug in SDL2 but it is easy to solve. Fix is [here](https://github.com/SpartanJ/eepp/commit/0e8cb66e9bd9589e6f29e509369c50886fec0e2c). Will be available in next release.
