### ISSUE TITLE
Soft-wrapping at chosen line length

### ISSUE THREAD

**Issue by glow12121** [SpartanJ/ecode#12]
Please consider implementing soft-wrapping text at a chosen length of line. This is very necessary while editing plain texts.

**Comment by SpartanJ** [comment]
This is planned but I want to implement other features first (multi-cursor, DAP). Soft wrap will require an important implementation change of the editor renderer. I personally don't use or even like word-wrapping, but I understand that it might be useful in some cases. I'll keep the issue open in the meantime.

**Comment by glow12121** [comment]
I guess it is important for people, like myself, who work with longer plain texts, 100-500 kbs in size.

In any case, good luck with the project.

**Comment by SpartanJ** [comment]
Sure, there will be different needs for every single user, but I hope someday to cover most users' needs.
It will be implemented, I hope the project to get some collaborators so we can speed up the development, right now it's just me with my little free time.

Thanks for the good wishes! =)

**Comment by SpartanJ** [comment]
Soft-wrap has been finally implemented, commit [here](https://github.com/SpartanJ/eepp/commit/3c033ed1931ebd41243444384167e44dde3f4106). It will be available for the next release.
