### ISSUE TITLE
[FEATURE] Encoding Selector?

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#126]
Did not find no encoding selectors and some documents with german symbols are broken so I'd have to toggle. Mostly there's no problems if you initially write these files in ecode but opening one from e.g. RAD Studio breaks all the german umlauts and renders the code to be all commented as some closing brackets vanish.

**Comment by SpartanJ** [comment]
Yes, this is a currently limitation given a design choice: the editor only supports [UTF-8 encoding as for the moment](https://github.com/SpartanJ/ecode?tab=readme-ov-file#current-limitations). It's not hard to add support for more encoding, but would add some dependencies and I wanted to keep it simple. But as it gets bigger I'll have to at least support most common encodings.

**Comment by SpartanJ** [comment]
Can you share any file so I can check its encoding and maybe it's some of the easy cases.

**Comment by NullPlane** [comment]
Well quite hard. I sadly lost the original I first had Problems with because I actually didn't look whether it was damaged and just saved it in its state... Idk if this still helps [but here it is](https://send.vis.ee/download/2f42e294c69f673c/#lu-_c3kTtWY4HQDwWdoHCg). I literally just changed something in the file's top section I cut away in this excerpt. Everything in there is just as I got it.

**Comment by SpartanJ** [comment]
Added support in the latest commits. For the moment we are going to support UTF-8, UTF-16 LE, UTF-16 BE and ISO-8859-1 (Latin1).
