### ISSUE TITLE
[FEATURE] File Type menu to Command Palette?

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#127]
Doesn't come up anywhere there, only menu. That'd be nice, once you boot it up, ctrl + t/n and then set the file type without using mouse but that's just secondary less important qol so just to add my thought I asked.

**Comment by SpartanJ** [comment]
It's a reasonable request. We already have some shortcuts for changing the build type and build ("sb " and "sbt "), so I could add "ft " for file type.

**Comment by SpartanJ** [comment]
Implemented [here](https://github.com/SpartanJ/eepp/commit/d7d56783c6ca0fbd617202740b11dd29058ae0e0).
