### ISSUE TITLE
 Optional Traditional Menubar

### ISSUE THREAD

**Issue by maddes8cht** [SpartanJ/ecode#128]
First of all:
Thank you so much for this great editor.
I was looking for a really fast, secondary editor for quick, everyday editing of any files, not as big as my VSCode that I use for various projects. Ecode is crazy fast, opens in an instant, as fast as Notepad, way faster than Notepad++ (which was my secondary Editor for a long time) , but has as many features as you could ever want! (Well, okay, VSCode can be configured as a full-fledged IDE that can do a few more things...) and looks and feels much better than Notepad ++...
Glad i found it!

So here is  my Feature request:
Please, add an option to have a traditional menu bar instead of the gear menu.

**Description**:
Currently, the Ecode editor features a menu accessible only through a symbol (a gear icon) in the top right corner. While proficient users can efficiently navigate using hotkeys, beginners or those less familiar with the shortcuts might benefit from a traditional menubar option. It would be much faster to access functions this way than by the gear Icon. With its *speed* being one of the key features, function selection via the menu should be fast too, even if one does not know the hotkeys (jet).

**Feature Request:**
I propose adding a switch in the settings to enable a conventional menubar display. This would allow users to access menu items directly from a visible menubar, enhancing accessibility for those who prefer a more visual and straightforward approach to navigation.

Again, thanks for the great work!
Not many people have heared about this Editor, but I wil recomend it to other people from now on!

**Comment by SpartanJ** [comment]
Thanks for your kind words. I think that it's a good idea to have it optionally and it's doable. I personally don't like missing the vertical space, and basically all design decisions are made to match my personal taste for now, but I'm more than open to provide alternatives to our users. I'd still prefer to keep the current default layout, but we can improve the keyboard bindings discoverability for new comers. I think that I'll add the shortcut to the menu (Ctrl/Cmd + M) in the Welcome screen.

**Comment by SpartanJ** [comment]
Menu bar has been implemented and it will be released in the next ecode version (0.5.2, coming soon). Some demo here:


https://github.com/SpartanJ/ecode/assets/650416/2301ced3-2292-4544-882f-b7bf69e24db8
