### ISSUE TITLE
Cannot open any files after closing an untitled tab

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#13]
Reproducing:
- Open a file
- Close the file
- An untitled tab opens up
- Close the untitled tab from the cross or using ctrl+w
- Can't open any files anymore, the Open Folder and Open File prompts in the settings menu don't do anything

If you write some text into the new untitled tab that appears after closing the old one and then close that, ignoring the warning, you can open files again

**Comment by SpartanJ** [comment]
Thanks for reporting it!
