### ISSUE TITLE
Crash when using color picker

### ISSUE THREAD

**Issue by thequver** [SpartanJ/ecode#131]
Select any hex color text to open color chooser -> select color picker -> press Esc to cancel -> program crash
[ecode.log](https://github.com/SpartanJ/ecode/files/14371773/ecode.log)

**Comment by SpartanJ** [comment]
Good catch, in that case I guess the picker should be canceled.

**Comment by SpartanJ** [comment]
Fixed [here](https://github.com/SpartanJ/eepp/commit/3ebb48c2e694f437859c201d77b6b14fef8ccf18). I changed the behaviour. First escape will cancel the color picking, the second escape will close the color picker window.
