### ISSUE TITLE
Feature request: syntax highlighting for SmallBASIC

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#136]
Syntax highlighting for other editors are here:

https://github.com/Joe7M?tab=repositories

You could use them as the references. Thank you.

**Comment by SpartanJ** [comment]
Hi! Given that there are some good references there, maybe you could collaborate to the project by adding the syntax highlighting yourself? If you don't feel brave enough I'll implement it later but seems a nice opportunity to collaborate. There's already also `Visual Basic` support that it might help you to implement it.
