### ISSUE TITLE
Unable to build ecode from source on MSYS2 (CLANG64)

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#141]
Please have a look at the build script. Something is wrong.

**Comment by SpartanJ** [comment]
Plase provide more information. Which package of MSYS2 you have installed? Can you show me the errors? I don't currently support it though, there are *many* distributions of msys2,clang,gcc,etc on Windows, I cannot support them all. [Here's](https://github.com/SpartanJ/eepp/issues/19) a thread were we talk about it.

**Comment by iahung3** [comment]
When building with MSYS2, don't use `mingw32-make`. Use `make` instead.
