### ISSUE TITLE
Feature request: let the users use the shell they want

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#146]
Related to: https://github.com/SpartanJ/ecode/issues/145 (maybe)

Don't restrict to PowerShell.

The users should be able to use whatever shells they want: Windows Command Prompt, MSYS2, Git Bash,...

**Comment by emeraldtip** [comment]
Already a feature:
![image](https://github.com/SpartanJ/ecode/assets/48155462/05f1be8a-f43a-432a-ae7c-6d1ec5cfd41a)

**Comment by iahung3** [comment]
> Already a feature: ![image](https://private-user-images.githubusercontent.com/48155462/309475579-05f1be8a-f43a-432a-ae7c-6d1ec5cfd41a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTk0MDIsIm5iZiI6MTcwOTM5OTEwMiwicGF0aCI6Ii80ODE1NTQ2Mi8zMDk0NzU1NzktMDVmMWJlOGEtZjQzYS00MzJhLWFlN2MtNmQxZWM1Y2ZkNDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE3MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODM2NGYyMThjMDY3OWExYzcyMmRiZTg1MjJiNGQxNGJmMWU5NWViNWNmYWVkMTFlNmMwYjBlNGQ5Y2MxM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJYbBimuXS4NHhtiWsrij26QL0GmqFuHm13RsQYx7U8)

Maybe. But it will not usable for me until https://github.com/SpartanJ/ecode/issues/145 is addressed. ecode depends entirely on Windows Terminal to provide the terminal features. So, even if I changed the shell to Windows Command Prompt, it still not work. `This feature is not supported in this Operating System`. This is the only thing it will ever tell me.

**Comment by iahung3** [comment]
Yes, I know about `eterm`. But it seems to be not what I need.

https://github.com/SpartanJ/eepp/tree/develop/src/tools/eterm

**Comment by Sakhi29** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
minhtq05, @evamvid, @pavelbonda, @joekraemer, @Sowul, @khai688668, @zyp001a, @sorajate, @kevaughngis, @seven1oe, @vallmeister, @lalghoul, @daggerhashimoto, @danav, @guigomesa, @bastienrobert, @sealhunt3r, @cluc-dev, @Umann2007, @lj3lj3

**Comment by SpartanJ** [comment]
Already supported.
