### ISSUE TITLE
Feature request: support Regular Expressions in search

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#147]
I'm pretty sure that the editor currently doesn't support Regular Expressions in Find/Replace. Only Lua Pattern is available.

**Comment by SpartanJ** [comment]
This is correct. I tried to avoid to add more complexity given that a fast PCRE implementation would require to add an extra dependency and a big one, which I'm not a fan of it. Using the std regex would be too slow for my taste, so I never decided what to do about it. Lua Patterns are awesome an very powerful, I encourage all users to learn and try them. [Here's](https://gitspartv.github.io/lua-patterns/) a good reference. Regex's will be added, but I'm still undecided on the "how".

**Comment by iahung3** [comment]
What is so wrong with `pcre2`? I found both Lite XL and Pragtical make use of it to support Regular Expressions.

**Comment by SpartanJ** [comment]
There's nothing wrong, it's just not as fast as I would like, but ecode will use PCRE2 given that it's the only library available with no dependencies. But the ideal library available is hyperscan. [Here](https://github.com/HFTrader/regex-performance/) you can see a good benchmark.

**Comment by iahung3** [comment]
> There's nothing wrong, it's just not as fast as I would like, but ecode will use PCRE2 given that it's the only library available with no dependencies. But the ideal library available is hyperscan. [Here](https://github.com/HFTrader/regex-performance/) you can see a good benchmark.

This benchmark result is not updated for 2 year. hyperscan itself is not updated for 1 year, too. Looking at the issues page of hyperscan, I have the impression that they abandoned it. PCRE2 is still the industry standard. Even if hyperscan is still being developed and has better performance, I still suggest you to just use PCRE2. It will always be the most full featured solution.

**Comment by SpartanJ** [comment]
Don't worry, PCRE2 will be used, it's already decided.

**Comment by chatchoi** [comment]
> Lua Patterns are awesome an very powerful, I encourage all users to learn and try them. [Here's](https://gitspartv.github.io/lua-patterns/) a good reference. Regex's will be added, but I'm still undecided on the "how".

It takes very long for me to get used to regex. I don't want to learn just another system that is irrelevant outside of the Lua world and this very text editor.

**Comment by chatchoi** [comment]
It took me very long to get used to regex. I don't want to learn Lua patterns.

**Comment by chatchoi** [comment]
This thing is for you:

https://github.com/Genivia/RE-flex

Github is so powerful. It knows what we are typing. It's becoming so dreadful. Right after I mentioned regex, it suggested me this. Your project is also suggested to me by Github this way. Oops. I remember it wrong. It's esfw first. I browsed the author's profile to see if I could discover other interesting things, then I found this editor.

**Comment by SpartanJ** [comment]
Feature implemented [here](https://github.com/SpartanJ/eepp/commit/a8214bbc23e04e108ae0d9087e06451534da0996).
