### ISSUE TITLE
Feature request: search in custom directory

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#151]
No folder needs to be opened. The users will need to specify the directory to search in.

**Comment by SpartanJ** [comment]
This will be implemented soon. It's pending.

**Comment by SpartanJ** [comment]
The way it was requested won't be implemented (searching in subdirectories from an open directory is already supported, but I don't think it makes much sense to search in a directory without opening it, user can open any folder any time if needs to do an specific search).
