### ISSUE TITLE
Feature request: search in a directory in the open folder

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#152]
For example, the open folder is `test` and it contains many directories, e.g: `test1`, `test2`,... I only want to do search in `test1`. Currently, it will search in the whole folder. It's awesome if I could right click on the directory `test1` and choose to search only in that directory.

**Comment by SpartanJ** [comment]
This is basically the same as #151.

**Comment by SpartanJ** [comment]
Oh, I indicated the wrong issue number, I was referring to #150 actually. This has been implemented.
