### ISSUE TITLE
Discussion: terminal for legacy Windows users

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#153]
Windows Command Prompt can't be embedded into the editor like Windows Terminal. But it can be launched in a new window. The embed terminal will definitely not available. This is the reason why I only consider this a temporary workaround. Actual solution is https://github.com/SpartanJ/ecode/issues/145

**Comment by iahung3** [comment]
> The terminal can't be embedded into the editor like Windows Terminal. But they can be launched in a new window.

@SpartanJ What do you think about this?

**Comment by SpartanJ** [comment]
So your idea is to simply open the configured default shell in a new process? I can do that.

**Comment by iahung3** [comment]
> So your idea is to simply open the configured default shell in a new process? I can do that.

This is useful enough for me. Please implement it. Thank you.

**Comment by SpartanJ** [comment]
Will do.
