### ISSUE TITLE
Feature request: syntax highlighting for Adept

### ISSUE THREAD

**Issue by iahung2** [SpartanJ/ecode#156]
References:

https://github.com/IsaacShelton/AdeptVSCode

https://github.com/AdeptLanguage/AdeptSublimeText

https://github.com/IsaacShelton/AdeptVim

https://github.com/iahung2/adept.geany.syntaxcoloring

**Comment by SpartanJ** [comment]
Issues are only closed after the bug-fix or feature are released in a stable release.
