### ISSUE TITLE
Feature request: view PDF inside ecode

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#168]

**Comment by SpartanJ** [comment]
Sorry but I don't want a PDF viewer inside ecode, I consider it out of the scope.

**Comment by iahung3** [comment]
> Sorry but I don't want a PDF viewer inside ecode, I consider it out of the scope.

Believe me or not, a PDF viewer inside a text editor is more common than you think. Except Electron based VSCode and friends, which got a PDF viewer for free, there are other text editors that do this:

https://github.com/adonais/skylark

https://texteditor.pro/

**Comment by SpartanJ** [comment]
I absolutely believe you, I just don't think an editor should be a PDF reader. I do see the possible benefit on some cases, for example for Latex editing or something alike, but ads a very heavy dependency for very little gain. I think it makes more sense for specialized editors.

**Comment by Curculigo** [comment]
> https://github.com/adonais/skylark

This is new to me. I don't know that SumatraPDF could be embedded into other applications!

**Comment by ghost** [comment]
SumatraPDF is just muPDF in disguise!
