### ISSUE TITLE
Text Rendered with Shadow

### ISSUE THREAD

**Issue by nfrozi** [SpartanJ/ecode#17]
I'm using the editor's light mode and solarobj as the style. On the 0.4.2 version, the text in the editor area is rendered with shadow. So, it becomes difficult to read. I've attached the screenshot figuring the comparison between the 0.4.2 and 0.4.1 versions here: https://pasteboard.co/e3RZGeq0Jdqq.jpg

**Comment by SpartanJ** [comment]
Oh, that seems like an unintended consequence of a fix I did for the latest release. It's a very easy fix but I will need to release a new version in order to fix it. I'll try to send a fix ASAP. Thanks for reporting it!
