### ISSUE TITLE
Feature request: insert UUID into the open buffer

### ISSUE THREAD

**Issue by iahung2** [SpartanJ/ecode#174]
Generate new UUID and insert into the open buffer.

**Comment by iahung2** [comment]
> I don't feel this is actually useful. How many times you require a random UUID to be inserted into the document? I find this very random to be part of the editor functionality, but I might be wrong.

What about implementing it as a plugin? The plugin is disabled by default?

**Comment by SpartanJ** [comment]
I have no problem accepting the contribution if someone implements the plugin. I won't develop it myself though.
