### ISSUE TITLE
FR: Use MSYS2 as terminal on older Windows

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#178]
I discovered that Netbeans is using Cygwin for terminal. So, ecode could do that, too. But I suggest using MSYS2 instead of Cygwin. The terminal emulator, mintty, is the same between Cygwin and MSYS2. But MSYS2 is more favored for native Windows development than Cygwin. Git Bash is also using MSYS2.

What I suggest is very simple. If the legacy Windows users have MSYS2 installed on their PC, ecode should use it for terminal. The default location for MSYS2 is `C:\msys64` (it's `C:\cygwin64` for Cygwin).

**Comment by SpartanJ** [comment]
I think I need to explain a little further why ecode does not support any terminal on older Windows, this is due a limitation on the older Windows API, it did not provide an easy way to create a pseudo-console, which was added really late to the Window API, the function we rely to create a terminal is [CreatePseudoConsole](https://learn.microsoft.com/en-us/windows/console/createpseudoconsole). Without that function it's complicated to create the terminal. The default shell used is just a minor detail in the implementation. But for sure, if powershell is not found I can fallback to msys2 or cygwin or whatever is present in the system.
