### ISSUE TITLE
Dont works on my Haiku-Os

### ISSUE THREAD

**Issue by GatoAmarilloBicolor** [SpartanJ/ecode#18]
Hello there i have try to test your software on haiku but i get this output:

```
ecode-haiku-0.4.0-x86_64> sh **ecode/ecode**
runtime_loader: Cannot open file libeepp.so (needed by /boot/home/Downloads/ecode-haiku-0.4.0-x86_64/ecode/ecode.bin): **No such file or directory**

```

But there is the libeepp.so, as it comes packed, did try to copy it to ecode root folder and nothing, dont know what happen here.

Haiku HREV: 56724

**Comment by SpartanJ** [comment]
You should run ecode bash script (not ecode.bin) in that version. But there's a newer version that fixes that, 0.4.2 is already [here](https://github.com/SpartanJ/ecode/releases/download/ecode-0.4.2/ecode-haiku-0.4.2-x86_64.tar.gz), in the latest version there's only `ecode` binary that will find the eepp library without any issues.
