### ISSUE TITLE
Feature Request: Shift Scroll and MMB Navigation.

### ISSUE THREAD

**Issue by shyperson0** [SpartanJ/ecode#181]
I've been using this editor exclusively so far but when trying to make a Spanish I discovered that ecode doesn't support Shift Scroll navigation.

Basically, holding Shift and Scrolling Down to Scroll Right, Shift+Scrollwheel Up to Scroll Left.

This feature would really improve usability for editing wide files, like translations and scripts.

tyvm

**Comment by SpartanJ** [comment]
TIL this exists! This is so obvious that I can't believe I didn't know about it. I'll add it really soon, it's trivial to add. Thanks for letting me know.

**Comment by SpartanJ** [comment]
Implemented, it will be available in next release.
