### ISSUE TITLE
FR: Behavior when file is being modified by an external process

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#197]
Please make it configurable. Other text editors will notify you and ask you if you want to reload the file from disk or keep the current content and mark the file as changed (this is configurable). ecode will auto-reload the file without notifying me that the file is being modified by an external process.

**Comment by SpartanJ** [comment]
[Done](https://github.com/SpartanJ/eepp/commit/db45a5a7eca04a48b93e258b2419cc332e673671). Auto-reload is now optional and configurable.
