### ISSUE TITLE
FR: Include some new fonts

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#198]
In addition to the existing fonts. These fonts are included in Pragtical: `FiraSans-Regular.ttf`, `JetBrainsMono-Regular.ttf`, and `icons.ttf` (I have no idea what this font is, you could download Pragtical and inspect it).

**Comment by SpartanJ** [comment]
Why? I don't see any good reason, you can use any font you like with ecode, but I don't see the point of adding some random fonts because some other editor use them.
