### ISSUE TITLE
FR: Update CMake lexer to support more keywords

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#205]
For example, keywords like `COMMENT` and `VERBATIM` are currently not highlighted:

https://github.com/AdeptLanguage/Adept/blob/master/CMakeLists.txt

**Comment by SpartanJ** [comment]
Maybe you can give me a hand with this one? You already know how to do it =)

**Comment by iahung2** [comment]
> Maybe you can give me a hand with this one? You already know how to do it =)

Where can I get a full list of CMake keywords? I can only add the keywords I found that are not properly highlighted when I read people's `CMakeLists.txt`.

**Comment by SpartanJ** [comment]
> Update: I can't help. Your addCMake() is a mess. How do you tell if a keyword is of type literal, keyword1, or keyword2? I really don't know!

😆 keywords use "keyword2", literals use "literal" and operators use "operator" haha sorry but that's all the logic behind. But yeah, don't worry, we can get the list from other editors, as always. As far as I saw in [this](https://github.com/SpartanJ/ecode/issues/204#issuecomment-2015784467) comment, CMake has a ridiculous number of keywords, we can add them with some patience.

**Comment by iahung2** [comment]
> > Update: I can't help. Your addCMake() is a mess. How do you tell if a keyword is of type literal, keyword1, or keyword2? I really don't know!
> 
> 😆 keywords use "keyword2", literals use "literal" and operators use "operator" haha sorry but that's all the logic behind. But yeah, don't worry, we can get the list from other editors, as always. As far as I saw in [this](https://github.com/SpartanJ/ecode/issues/204#issuecomment-2015784467) comment, CMake has a ridiculous number of keywords, we can add them with some patience.

By what logic that you have `APPEND` as `literal`? I really don't understand!

https://github.com/SpartanJ/eepp/blob/bdcf47dfebb1fe2bb7be1ea33d9650914e1cdce5/src/eepp/ui/doc/languages/cmake.cpp#L35

**Comment by iahung2** [comment]
> I might do it myself.

Please help me this time. Thank you.
