### ISSUE TITLE
Unable to display Vietnamese

### ISSUE THREAD

**Issue by superchick** [SpartanJ/ecode#209]
Copy and paste this into your editor:

```
Trăm năm trong cõi người ta,
Chữ tài chữ mệnh khéo là ghét nhau.
Trải qua một cuộc bể dâu,
Những điều trông thấy mà đau đớn lòng.
```

**Comment by iahung2** [comment]
Use Liberation Mono font. It correctly displayed the text.

**Comment by SpartanJ** [comment]
I'll try to provide a default font for Vietnamese in the next release.

> Use Liberation Mono font. It correctly displayed the text.

MMhh it's really similar to DejaVu Sans Mono but it seems to cover more glyphs, and it looks really nice, I might change the default monospaced font 🤔 .

**Comment by superchick** [comment]
Still a problem: https://github.com/SpartanJ/ecode/issues/210
