### ISSUE TITLE
Opening the same folder multiple times in a row causes terminals to duplicate Windows

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#22]
Initial:
![image](https://user-images.githubusercontent.com/48155462/216094128-4efbe86d-489e-4be4-9ca2-27dfe7c4f49d.png)
After opening the same folder again:
![image](https://user-images.githubusercontent.com/48155462/216094179-bc97dfee-a2a5-4890-b95b-e0243f4e4e74.png)
And again:
![image](https://user-images.githubusercontent.com/48155462/216094251-9a7119b5-9dfe-4b02-a018-9cc5f601ff83.png)

**Comment by SpartanJ** [comment]
I think I don't understand the bug, I tried doing what you describe and nothing weird happened. Can you record a video showing how it happens? Thanks

**Comment by emeraldtip** [comment]
https://user-images.githubusercontent.com/48155462/216272657-21f67ed2-cfd5-401e-b95f-4df72b2d89d9.mp4

**Comment by SpartanJ** [comment]
Great, now I understand. Thanks!
