### ISSUE TITLE
FR: setup Nightly build

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#228]
Like this: https://github.com/AdeptLanguage/Adept/releases/tag/Nightly

Or this: https://github.com/pragtical/pragtical/releases/tag/rolling

Will help people that can't build their own version of `ecode` from latest code: https://github.com/SpartanJ/ecode/issues/227

**Comment by SpartanJ** [comment]
Yes, I think I'll try to setup a nightly build, also because building all the packages for a new release is currently a manual process where I depend on several computers.

**Comment by Curculigo** [comment]
Believe it or not, I decided to learn C++ with this very old laptop that only has 4GB of RAM. I can't effort compiling from source to access the latest fixes. A Nightly build will really help. I don't want to wait for months to get a new release!

**Comment by SpartanJ** [comment]
I'll try to set it up soon. I'm not very familiar with Github Actions and I was being a little lazy because of that.

**Comment by SpartanJ** [comment]
Nightly builds for Linux and Windows should start producing since [this](https://github.com/SpartanJ/eepp/commit/e789c15022a720186542fc15bcb51eeb8d3845db) commit. They will be found [here](https://github.com/SpartanJ/eepp/releases/tag/nightly).

**Comment by SpartanJ** [comment]
Update notifications won't happen for the moment unless your nightly is older than a released build, nightly takes the next-release version (currently 0.6.2). It's needed a different versioning for nightly, so not for the moment.

As for self-updater is pending for all kind of releases. It's kinda tricky since there are several different distribution types (AppImage, zip/tar.gz, dmg, flatpak, and also in distro/OS repositories).

**Comment by chatchoi** [comment]
You can add the build number or the timestamp to the version string.

**Comment by SpartanJ** [comment]
Yeah, `git describe` could come handy, but I need to change how releases are checked internally and patch the version number in code. It's not hard, but as everything, takes some time.

**Comment by SpartanJ** [comment]
Nightly builds started having a release number version different from the stable releases, this allows to notify if there's a new stable version newer than the nightly build you're using. I decided not to report for new nightly builds given that there's a new one every single day, I prefer to notify about stable releases.
