### ISSUE TITLE
FR: code-folding

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#231]
Lite XL and Pragtical seem to not support code-folding. So, none of the Lite-based code editors currently support code-folding. It seems existing lexers will need to be modified to include code-folding rules (like what of `scintillua`).

**Comment by SpartanJ** [comment]
Code folding has been implemented, commit [here](https://github.com/SpartanJ/eepp/commit/851dfc3ccb0f44d475d76693a32154783e04c3cd) plus the implementation of [soft-wrap](https://github.com/SpartanJ/ecode/issues/12) should close all the pending "basic" functionalities for a code-editor. Both features will be available in the next ecode release.
