### ISSUE TITLE
Sublime Text Syntax Definitions

### ISSUE THREAD

**Issue by superchick** [SpartanJ/ecode#236]
Import and use .sublime-syntax file. Use directly or translate to native format is up to the developer.

https://www.sublimetext.com/docs/syntax.html

**Comment by SpartanJ** [comment]
My answer is the same as [here](https://github.com/SpartanJ/ecode/issues/191#issuecomment-1995098605). Plus the definitions are based on some syntax rules that doesn't seem to translate directly to ecode rules, so it looks harder than TextMate language definitions.
