### ISSUE TITLE
Optimized builds?

### ISSUE THREAD

**Issue by superchick** [SpartanJ/ecode#237]
AVX2.

Example:

https://github.com/zufuliu/notepad2/releases/download/v4.24.03r5146/Notepad2_en_AVX2_v4.24.03r5146.zip

**Comment by SpartanJ** [comment]
Optimised builds sound awesome on paper but compiler very rarely is able to vectorise any operation with AVX2 (you kind of need to be explicit for these kind of vectorisation). So you'll end up with a set of confusing builds that they'll vary on performance in less than 1%.
If we encounter any performance issue it should be solved for everyone and not rely on CPU extensions.
