### ISSUE TITLE
HiDPI support?

### ISSUE THREAD

**Issue by superchick** [SpartanJ/ecode#238]
Are you have HiDPI edition, like this?

https://github.com/zufuliu/notepad2/releases/download/v4.24.03r5146/Notepad2_HD_en_AVX2_v4.24.03r5146.zip

**Comment by emeraldtip** [comment]
![image](https://github.com/SpartanJ/ecode/assets/48155462/07cfbfcf-f4e9-4930-a378-f34cd42189e4)
![image](https://github.com/SpartanJ/ecode/assets/48155462/6f69071b-c09e-4397-a5c3-6250a5063761)

So in short, yes it does have a dpi setting

**Comment by SpartanJ** [comment]
ecode (eepp GUI) supports non-integer scaling, and it will auto scale the UI depending on your screen DPI by default, and it can be configured at any time.
