### ISSUE TITLE
[0.4.3] Open Folder should open the last folder opened instead of ecode.exe path

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#24]
I believe it would be useful for Open Folder command to default to the last folder opened (which should be the current folder being used) instead of what it does currently, which is to show the folder of the ecode.exe file.  

Each time I go to browse to a folder I have to navigate from the ecode.exe folder instead of the folder where all of my code projects are located.

I think it would be widely appreciated.

Thanks for the awesome editor, can't wait to see it grow!

**Comment by SpartanJ** [comment]
Thanks for the kind words. That option is already available, but it's not set by default (I'm considering changing it to the default behavior, let me think about it a little bit).
Anyway, you need to check this item:
![212567535-0eed5472-499c-4c5e-877e-0df0be2e00d7](https://user-images.githubusercontent.com/650416/216387936-2733963a-9a92-4c40-84db-270b6771c661.png)

**Comment by andy0x10** [comment]
Sorry, this is not what I'm referring to.

I mean, each time I go to Open Folder to select a new folder, Windows always reverts the Open Folder Dialog to show the ecode application path.  It would be more useful to show the last/current folder as the default.

I hope that makes sense.

Thanks,
