### ISSUE TITLE
Set lexer for custom file extension in `config.cfg` doesn't work

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#246]
I followed the instruction here: https://github.com/SpartanJ/ecode/discussions/194

I edited `config.cfg` to add `winlib=shellscript`. Doesn't work. This means I can't register new file extensions in `config.cfg`.

**Comment by SpartanJ** [comment]
That configuration is not for setting a custom file extension, but for setting the default language for a file extension (when a file extension can represent more than a single language). Currently it's not possible to register custom file extensions.
