### ISSUE TITLE
Bug: Some Global Settings are not saved

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#248]
`Trim Trailing Whitespaces` and `Force New Line at End of File` will be automatically unchecked the next time you start `ecode`.

**Comment by SpartanJ** [comment]
I'm unable to reproduce it.

**Comment by SpartanJ** [comment]
Can you record a video demonstrating the issue? I tried *many* ways and I'm still unable to reproduce it.

**Comment by iahung3** [comment]
Discover: It will only work if you open a file before you set the settings. I didn't open any files.

**Comment by SpartanJ** [comment]
Ohh very nice catch. Thank you, it's already fixed.
