### ISSUE TITLE
[0.4.3] Request for C# formatter support

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#25]
Request for C# formatter support please

**Comment by SpartanJ** [comment]
I need to add support for [OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn) LSP. I wasn't able to run it from Linux and got a little frustrated. Do you know any C# formatter? I'm not very familiar with the .NET environment but it shouldn't be hard to find one.

**Comment by SpartanJ** [comment]
[uncrustify](https://github.com/uncrustify/uncrustify) could be an option. I'll keep investigating.

**Comment by andy0x10** [comment]
Yeah I'm not familiar with any so I can't make a recommendation.  I did just try the offical Microsoft ones, but they didn't seem to support single .cs files and require a .csproj / .sln as well as far as I could tell...

Thanks I will look at uncrustify 👍

**Comment by andy0x10** [comment]
Great that's it's now supported in 0.4.4! 👍 

But...I can't figure out how to use it to format C# code?  I've installed Omnisharp and added it to the path.  Anything else required?

Also, you should maybe add the new C# Omnisharp support to the readme.md page

Thanks!

**Comment by SpartanJ** [comment]
I think it's broken on Windows (I'm assuming that you're on Windows). I made a fix a couple of days ago. I didn't test OmniSharp on Windows yet, but Clang was fixed. You can give it a try:
[ecode-windows-0.4.4-x86_64.zip](https://github.com/SpartanJ/ecode/files/10688449/ecode-windows-0.4.4-x86_64.zip), please let me know. Also try to run ecode with debug logs: `ecode.exe -ldebug` and if it doesn't work just send me the logs. Thanks!
