### ISSUE TITLE
FR: Support to open multiple files from "Open File"

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#252]
Current button's name, `Open a File`, is very clear that it can only open a single file.

**Comment by SpartanJ** [comment]
Yes, this is pending, I never cared enough to fix it (I don't see the point of opening a file form "Open file...", if i need to open many files i'll drag the files to ecode.

**Comment by iahung3** [comment]
> if i need to open many files i'll drag the files to ecode.

I will do like you.

**Comment by SpartanJ** [comment]
I still want to do it, I'm gonna keep it open.

**Comment by SpartanJ** [comment]
> Pressing Ctrl to select multiple files and Shift to select a block of files?

Yes

> If multiple files could be selected and opened, how would the search feature work?

Selection should be kept alive while filtering. But it's tricky, so initially I will not care about it. Not even Dolphin supports it, so we will be fine without it.
