### ISSUE TITLE
FR: Open files from opened folder improvement

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#254]
Assuming the number of files in the folder is very large and the users know exactly which files they want to open, should there be a text box so users could enter the name of the file they want to open? Think a bit further: should that text box allow the users to search for files whose names match the name or the patterns they entered?

**Comment by iahung3** [comment]
> if i need to open many files i'll drag the files to ecode.

I will do like you.

**Comment by iahung3** [comment]
@SpartanJ What do you think about this? I want to know your opinion.

**Comment by SpartanJ** [comment]
It makes sense as an improvement for the file picker dialog, I don't consider it particularly important.
This is the best to do it IMO (plus accepting glob patterns):


https://github.com/SpartanJ/ecode/assets/650416/18d5b235-77a6-4f57-8001-e9a1f41778df

**Comment by iahung3** [comment]
> It makes sense as an improvement for the file picker dialog, I don't consider it particularly important. This is the best way to do it IMO (plus accepting glob patterns):
> 
>  2024-04-15_14-56-58.mp4

So you want to implement the feature in the `Open File` dialog instead? Because in this FR, I'm talking about opened folder. It will be something like a search button next to the build setting button. Click on it and enter the file name or patterns into the text box to search for files in the opened folder.
