### ISSUE TITLE
FR: synchronize the location in `Open File` with the currently opened folder

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#255]
I opened directory `A` as folder in `ecode`. By default, `Open File` will start with directory `A`. But if I switch the location to another directory, could be outside of `A`, then the next time I use `Open File`, it will start with that directory. Should there be a way to switch back to directory `A` without having to browse manually? Maybe a magic button that will immediately switch back to `A`?

**Comment by iahung3** [comment]
Update: Why don't I just open a file in the opened folder via the directory tree in the left pane? It will default to the directory that contains the last opened file anyway. How silly I am!

**Comment by SpartanJ** [comment]
The editor is designed to be mainly used with keyboard and the preferred way of opening a file is by using the fuzzy file search with CTRL+K. And to execute a command is always preferred to  use the command palette with CTRL+P. You should try to get used to that and you won't pick the mouse for trivial things anymore =)
