### ISSUE TITLE
FR: a single mouse click to open items

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#256]
Currently, for all dialogs (`Open File`, `Open Folder`, `Save`, `Save As`, etc.) and the directory tree of an opened folder displayed in the left pane of `ecode`, it needs a double click to open items. Please make this configurable so people who prefer single click or double click can choose their desired option. The default is still double-clicking.

**Comment by SpartanJ** [comment]
This is actually planned.

**Comment by SpartanJ** [comment]
"Single Click Navigation in Tree View" is now "Single Click Navigation" and activates single click navigation in file dialogs too.
