### ISSUE TITLE
FR: Support registering custom file extensions for syntax highlighting

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#261]
Extension `config.cfg` to add something like:

```
[custom_languages_extensions]
vala=csharp
```

Note: I choose `vala=csharp` as an example because these two languages are very similar and I assumed that built-in syntax highlighting for Vala is not yet available.

**Comment by SpartanJ** [comment]
I'm not interested in this feature, if a file extension is incorrectly not supported users should report it and get a global fix for everyone. "Local" fixes aren't the correct solution. If anyone wants to support a new language already have [all the tools provided by ecode](https://github.com/SpartanJ/ecode?tab=readme-ov-file#custom-languages-support) to do it, even exporting a base language from the command parameters provided by ecode:

```
      --export-lang-path=[export-lang-path]
                                        Export language definitions to the file
                                        path. If no "export-lang" is defined it
                                        will export all languages available.
      --export-lang=[export-lang]       Comma separated language names to export
                                        its language definitions.
                                        "export-lang-path" must be defined.
```
