### ISSUE TITLE
Discussion: ctags and code completion

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#263]
Geany has supported displaying symbols table and tag-based code completion (not the normal word-based code completion) using tag parser long before Tree-sitter became a thing. What do you think about leveraging ctags?

**Comment by SpartanJ** [comment]
Mhh I think it doesn't make any sense in the LSP era, it's a very basic solution that has no place in 2024 (I have used Geany for many years, ctags were never great). LSP's provided much superior code-completion, so we should strive to have LSP support for every language that has an LSP, so we simply need to add the LSPs to ecode when they are created.
