### ISSUE TITLE
[0.4.3] Invisible character giving inconcistent editing experience

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#27]
Sometimes it seems like an invisible character appears which means that when I use arrows to navigate the cursor doesn't move on the first press, only the second.  It also results in when pressing delete it will delete the wrong character.

![image](https://user-images.githubusercontent.com/124288474/216395060-be59743a-caa5-4ada-93ae-402f87c8f884.png)

Here there is an invisible character after the "{" if you position the cursor after the "{" then press right-arrow it will not move until the second press.

Also, if you position the cursor just before the "V" on line 3, then press backspace, it will delete the V instead of the space.

I think that this may be related to #26 

I am using Windows.

The example file is attached:
[TestBug2.cs.txt](https://github.com/SpartanJ/ecode/files/10571576/TestBug2.cs.txt)

**Comment by andy0x10** [comment]
The file needs to be renamed to .cs for the bug to be demonstrated

**Comment by SpartanJ** [comment]
One question: The original file was edited in ecode? The problem is the new line, it's using CRLF. I think this is a save issue when CRLF is enabled.

**Comment by andy0x10** [comment]
Yes the code was written in ecode...but it's possible that I pasted some of it from somewhere else...I can't remember...I started this codebase a few weeks ago and have only been using ecode for editing.

**Comment by SpartanJ** [comment]
That's a key detail! I think this must come from copy-pasting code that uses CRLF as line endings. Makes total sense since I never take it into account. I'll take a look at this, it's really important.
