### ISSUE TITLE
Vue codes in <script> doesn't have syntax highlight

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#275]
![image](https://github.com/SpartanJ/ecode/assets/68846168/a26c4778-947b-4678-bc04-1b6a7fdf92a5)

**Comment by SpartanJ** [comment]
Thanks for the report, it's already fixed in dev. Meanwhile you can use the patched language definition 
[vue.json](https://github.com/SpartanJ/ecode/files/15243699/vue.json).
You can install that file into the [custom languages path](#custom-languages-support).

**Comment by zhaolinlau** [comment]
@SpartanJ when i put a `'`, it will break the syntax highlight

result with `'`
![image](https://github.com/SpartanJ/ecode/assets/68846168/1bd3eac8-1ef7-4f2f-bd7f-e127ddc70304)

result without `'`
![image](https://github.com/SpartanJ/ecode/assets/68846168/5a4eb928-a52c-4288-9392-34db2778d7bb)

**Comment by SpartanJ** [comment]
Oh, thanks! That was an actual bug on the tokenizer

**Comment by SpartanJ** [comment]
Here's an updated build: [ecode-windows-0.5.2-x86_64.zip](https://github.com/SpartanJ/ecode/files/15251509/ecode-windows-0.5.2-x86_64.zip)
