### ISSUE TITLE
FR: Shift-JIS support

### ISSUE THREAD

**Issue by shyperson0** [SpartanJ/ecode#276]
Pretty much title, a lot of coleagues use Shift-JIS instead of Unicode, I'd like to keep all my work within ecode instead of having to use a different editor for Shift-JIS files.

**Comment by SpartanJ** [comment]
[This](https://github.com/SpartanJ/eepp/commit/156774d80f6c1baf244c18977a9e117267c4e143) commit adds Shift-JIS support. Feature should be ready but I'll test it a little bit more, since he heuristics to determine if a file is encoded with Shift-JIS are quite tricky.
