### ISSUE TITLE
powershell is being opened externally on windows

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#277]
For now, when i press ctrl + shift + t, it does open the terminal but externally, is it possible to make it open internally?

**Comment by zhaolinlau** [comment]
im using latest version of powershell:
https://github.com/PowerShell/PowerShell

**Comment by SpartanJ** [comment]
If it opens externally it's because you're using an old Windows (probably 8/8.1). It's not possible due to a Windows 8 limitation. This was added as an alternative to the limitations of the OS, otherwise terminals always open as a new tab.

**Comment by SpartanJ** [comment]
More info: https://github.com/SpartanJ/ecode/issues/145, https://github.com/SpartanJ/ecode/issues/178 and https://github.com/SpartanJ/ecode/issues/207.
