### ISSUE TITLE
Allow opening `ecode` with a blank document (bypass welcome tab)

### ISSUE THREAD

**Issue by whatbh** [SpartanJ/ecode#279]
Currently when opening new `ecode` window brings users to a "welcome page" and having to press <kbd>Ctrl</kbd>+<kbd>T</kbd> to open new file. I would love to have an option to allow users to open new `ecode` window with a blank document readily. 

Out of the scope, I anticipate that in the future, a dedicated "Preferences" page or maybe a config file in a markup/serialization format would greatly facilitate these kind of opinionated fine-tuning, instead of leaving them scattering among the menus?

<details>
    <summary>Compliment</summary>
    Lastly, I want to say thank you very much for making this too-good-to-be-true editor available. To me, this one is awesome in many way, it preserve most of the ergonomics from Sublime Text so I never have to leave behind my muscle memory. I also come with a lot of batteries included, like a minimap and, to my surprise, a built-in terminal emulator.
</details>

**Comment by whatbh** [comment]
> ...also, it used to be like that before the "Welcome Page" existed.

Good to know about this one 😛

> Small tip: if you're configuring the editor from the menus you can press "shift" while setting an option and the menu will be kept open. IDK how to communicate that to the users, but it's important since otherwise it's annoying to configure multiple settings at once.


Mindblown! TBH knowing this transforms my (and probably others) experience with menus significantly. Keeping menus open like this add great convenience setting up options, maybe even for options that would otherwise buried deep in Setting panel or JSON file. 
I am no expert but personally I think I would have know this sooner if there some note like this directly in the menu.

![Screenshot 2024-05-16 153242](https://github.com/SpartanJ/ecode/assets/91888303/65efb084-ac94-4497-9480-c5fcf5db07bc)

**Comment by SpartanJ** [comment]
Added the option to disable the Welcome Screen:
![Screenshot_20240602_233653](https://github.com/SpartanJ/ecode/assets/650416/e68f92f4-cef7-4ca4-a2cb-1e612affc341)
![Screenshot_20240602_233725](https://github.com/SpartanJ/ecode/assets/650416/3ebcd7ef-979a-471f-9a98-f65143507306)

(And also the "Hold Shift" suggestion, I'm not convinced but I'll leave it there for the moment).
