### ISSUE TITLE
[SUGGESTION] $FILEPATH etc. in LSP Client

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#284]
For jdtls specifically they do not enforce but kindly ask to have a project-respective dir in your current working dir or elsewhere. I think some vars in there may be helpful to some LSPs but maybe there are already such and I just did not find them.

**Comment by SpartanJ** [comment]
For the moment we only use [$FILENAME](https://github.com/SpartanJ/eepp/blob/develop/bin/assets/plugins/formatters.json#L18) which is actually the file path and not the name 😅, I guess I can add `$PROJECTPATH`, I cannot think any other though. I don't like I used `$ALLCAPS`, I might add the alternative that we use for the build system, they look like: `${project_root}`.

**Comment by SpartanJ** [comment]
[Added](https://github.com/SpartanJ/eepp/commit/e54c7dee4fa4a1c7e20639221ad520da9724f965) `${project_root}` (or `$PROJECTPATH`) as keywords for commands in LSP, Formatter and Linter.
