### ISSUE TITLE
Unsaved mark exceeds tabwidth

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#287]
Idk how to classify this.
In short: If the filename is very long the `*` asterisk vanishes
to mark it unsaved.

**Comment by SpartanJ** [comment]
Ohh, because the * goes at the end of the filename, so it gets cut, I didn't think about it when I added the ellipsis and never noticed. Let me think how to solve it. May it's time to remove the asterisk all over.

**Comment by SpartanJ** [comment]
I removed the asterisk in favor of a visual color indicator:
![Screenshot_20240630_203355](https://github.com/SpartanJ/ecode/assets/650416/a799ba94-5c47-4d62-abd4-dc4025b9a547)

I think it looks better but it worries me a little if color blind people can perceive it (for me it's perfectly obvious but I'm not color blind).

I might add a circle like in vscode but I'm not convinced.

**Comment by SpartanJ** [comment]
Issue #69 is a request for a better distinction for saved and unsaved files, so this change is relevant for both issues.

**Comment by SpartanJ** [comment]
Mmh changed my mind, current version:
![Screenshot_20240701_214746](https://github.com/SpartanJ/ecode/assets/650416/4a5b0e63-b322-4077-a044-d2f25e41deac)

**Comment by NullPlane** [comment]
looks fresh.
What'll be the var in the ui styling?

**Comment by SpartanJ** [comment]
The UI can be styled with CSS as always. You can create a [custom theme](https://github.com/SpartanJ/ecode?tab=readme-ov-file#custom-ui-themes) or use the `--css` command parameter. [Here's](https://github.com/SpartanJ/eepp/commit/3d59b3c64be7d8bd1ec43e0d0ff13d2b03c2cb0e#diff-5bc8efe589d143557325162055fd2f48e1d358fa6aedf3fa8ad275e085466257R425) the new CSS.
