### ISSUE TITLE
Add a mechanism to enable hiding files from opened folders in the project tree view

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#29]
Unity creates *.*.meta files for each file in the project:
![image](https://user-images.githubusercontent.com/124288474/216398196-6f211823-a614-4427-8b68-61969b2a2606.png)

Is there any easy way currently to hide there?  Perhaps a future feature/option....

Thanks,

PS Sorry for the bombardment.  I like your editor and just reporting the minors issues I've spotted.  Last one for today :-)

**Comment by SpartanJ** [comment]
This feature should be more generic. But I already had something similar in mind. What we need is a per-folder/project filter, basically like a .gitignore but customized for the folder tree view. I'll change the title of the issue to reflect the feature.
Don't worry about the number of issues opened, I don't mind and it's useful for the project, I'm glad that people started using the editor.

**Comment by andy0x10** [comment]
Great, I agree!

Just a side note - for the Unity .meta files, they are always added to version control, so they'd never appear in .gitignore

👍

**Comment by SpartanJ** [comment]
Yes, that's clear! I think that it should be filtered separately, we will not use the .gitignore for this feature.
