### ISSUE TITLE
[ENHANCEMENT] LSP Switch

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#290]
Some software need different commands for their lsp servers.
E.g. there is a lsp you want to use for dummying with the help
of an API that shall not print all errors because the dependencies
are missing. Maybe later on you get those and need to implement
the stuff that was missing before. You may now use the full-fledged
hyperresponsive LSP.

Switching off diagnostics is not the best option here if you still need
certain functionality...

Having profiles would actually be useful if more people needed such
implementation. It'd be a charm to just toggle a different profile and
then refresh the plugin to the new lsp type.

**Comment by SpartanJ** [comment]
It does sound cumbersome with very little benefit, you can already disable temporarily the linter (which disables LSP diagnostics) with a single switch. You can also keep the linter working but disable the LSP diagnostics (linter config `enable_lsp_diagnostics`), and you can also disable specific languages for linting or LSP diagnostics. I think that it's more than enough for now, I understand that you want something like LSP and linter per-project configuration, but this is not something for the editor to provide but for the LSP or Linter, by allowing the user to set a per-project configuration in a config file at the root of the project, like clang for example, this is something that exists in many LSPs and linters, so you might still be able to achieve this in your particular case.
