### ISSUE TITLE
New Folder?

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#298]
I know the editor uses folder and project as synonym. But this is when this fall apart. I need the ability to create new project from the editor. I found there is currently no such feature. Btw, what name will you give to it? New Folder, or New Project?

I want to be able to close a project, too. Currently, this is done by opening a new folder, as it will immediately switch to the newly opened folder/project. But what if I simply want to close the current project without opening a new project?

**Comment by SpartanJ** [comment]
> I need the ability to create new project from the editor.

You can currently do it in the same way that most editors: go to "Open Folder..." and create the new folder from the file/folder dialog and simply open it. I don't think that anything else is needed (all popular editors work the same way and I agree with the design decision).

> I want to be able to close a project, too.

You can also do it: it's called "Close Folder", from the Settings menu or the command palette.
