### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#299]
Can you provide binary builds for FreeBSD?

**Comment by SpartanJ** [comment]
I don't think there's actually demand for this right now but it could be implemented with #228 which simplifies all the work required.

**Comment by SpartanJ** [comment]
FreeBSD build [has been added](https://github.com/SpartanJ/ecode/releases/tag/ecode-0.6.0) and now is officially supported.

**Comment by SpartanJ** [comment]
Build script is [here](https://github.com/SpartanJ/eepp/blob/develop/projects/freebsd/ecode/build.app.sh).

**Comment by SpartanJ** [comment]
Also: FreeBSD is not supported by Github Actions, so nightly builds for FreeBSD won't be possible.
