### ISSUE TITLE
macOS "About ecode" version is inconsistent

### ISSUE THREAD

**Issue by dguenther** [SpartanJ/ecode#3]
The macOS "ecode -> About ecode" menu displays this version:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/767083/211611810-68abd621-0e0e-4e1c-b488-1073bfa3eb69.png">

Whereas ecode's "Help -> About ecode..." menu displays this version:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/767083/211612267-6301d0ba-6011-4329-ad31-9424dfa8fa4e.png">

Admittedly a trivial issue, apologies!

**Comment by SpartanJ** [comment]
Oh, trivial but important! Thanks for reporting it.

**Comment by SpartanJ** [comment]
Fixed!
