### ISSUE TITLE
How to show/hide hidden files and folders?

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#300]
`Ctrl+H` doesn't work. I want to edit `.bashrc`.

**Comment by NullPlane** [comment]
For now just add it to your path.
Go `$EDITOR ~/.bashrc` and add an alias for ecode in your directory to call it from shell.
Then just `ecode ~/.bashrc`. If you're not working on a project in a project
directory in-editor filelists are generally not the best-case usage option.

**Comment by SpartanJ** [comment]
You can open the directory and then over the file-tree press right click and "Show hidden files". But usually for any file in the file-system you'll want to just simply configure your file manager to open text files with ecode and that's enough.

**Comment by SpartanJ** [comment]
Please for questions use the Discussions section [here](https://github.com/SpartanJ/ecode/discussions/categories/q-a).
