### ISSUE TITLE
New shortcut keys for build and run features

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#307]
`F5` -> Run
`F9` -> Build
`Shift+F9` -> Build and Run (currently is mapped to `F5`, I suggest change to `Shift+F9` to reserve `F5` for Run)

**Comment by SpartanJ** [comment]
You can remap it at your liking, I won't change it.

**Comment by Curculigo** [comment]
> You can remap it at your liking, I won't change it.

How?

**Comment by SpartanJ** [comment]
Settings -> Edit -> Keybindings
