### ISSUE TITLE
Interpreted languages with build and run features

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#308]
If I left the Build step empty, it will error:

```
The process "" exited with errors.
Build run with errors
```

I don't know what I should have for the Build step.

**Comment by SpartanJ** [comment]
Just don't use the build step, remap your keybindings to just run it (command is "project-run-executable")

**Comment by SpartanJ** [comment]
Tip: You can find unmapped commands on the command palette, second column will display its command name and can be added to the `[editor]` keybindings.
