### ISSUE TITLE
How long is a single line?

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#311]
I have a large JSON generated by a program. It's about 10MB. In the beautified (formatted) form, ecode has no problem loading it. But if I minify it (compress it into a single line), ecode will fail to load it and crash.

**Comment by SpartanJ** [comment]
I don't expect ecode to handle well a single line 10MB file, it's not designed for that, but I've opened many big single line files in the past, so I can check why it crashed if you share the file. Usually using soft-wrap will give you better results if you insist in editing a huge single line file. But this will be expensive in ecode or any other editor. Regarding the question in title, IDK what you mean, a single line is as long as it's size, there's no harcoded limit.
