### ISSUE TITLE
View images inside editor

### ISSUE THREAD

**Issue by vmz9poa5** [SpartanJ/ecode#321]
I saw a text editor displaying a .gif image on Github today. This is cool. Windows Image Viewer sucks. If ecode add this feature, I think I will set it as the default PNG and JPG/JPEG viewer (and if it supports WebP then it will be the default WebP viewer, too) 😃

**Comment by Curculigo** [comment]
@SpartanJ This seems to be something already possible, isn't it? I just opened a JPG image by dragging it into ecode.

**Comment by SpartanJ** [comment]
Yes, it does support several images format for preview. There's a request for improvements on the image viewer [here](https://github.com/SpartanJ/ecode/issues/96).
