### ISSUE TITLE
How to open the `Welcome` page manually?

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#323]
I'm kind of like it. It lists all of the popular functionalities. I don't have to go to Menu or dive into the command palette. Everything is just there.

**Comment by SpartanJ** [comment]
So you want to be able to open the Welcome page without going to the menu or command palette, with just a shortcut?
Otherwise a Welcome page will show up is you open a new window or close the current folder, both can be binded with a shortcut.

**Comment by Curculigo** [comment]
> So you want to be able to open the Welcome page without going to the menu or command palette, with just a shortcut?

Is it possible to open the Welcome page via the Menu or the command palette? I don't know that it's possible. Please let me know how. I'm still new to ecode.

> Otherwise a Welcome page will show up is you open a new window or close the current folder, both can be binded with a shortcut.

Yes, I know. But I want to be possible to open the Welcome page when I have opened a folder.

**Comment by SpartanJ** [comment]
Gotcha, no, it was not available, so I added [here](https://github.com/SpartanJ/eepp/commit/ba860d7164a2661e8571ec84c768fdd5ccf8ecf3) a new command called "create-new-welcome-tab", so you can use it from the command palette or bind a new keybinding to create the welcome tab (it won't have any binding by default).

**Comment by Curculigo** [comment]
> Gotcha, no, it was not available, so I added [here](https://github.com/SpartanJ/eepp/commit/ba860d7164a2661e8571ec84c768fdd5ccf8ecf3) a new command called "create-new-welcome-tab", so you can use it from the command palette or bind a new keybinding to create the welcome tab (it won't have any binding by default).

Why not "open-new-welcome-tab"?

**Comment by SpartanJ** [comment]
Because "create-new*" is already used for the rest of the commands to create new tabs of different types.
