### ISSUE TITLE
CMake syntax highlighting bug

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#326]
This particular file troubled ecode's syntax highlighter engine:

https://github.com/cnjinhao/nana/blob/a9398c1a4a855218b6b02bcf86969b38f6a892b7/build/cmake/compilers.cmake

Github highlights it correctly, ecode will consider this line as a comment:

```
if(CMAKE_COMPILER_IS_GNUCXX OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang") #  AND NOT MINGW??
```

https://github.com/cnjinhao/nana/blob/a9398c1a4a855218b6b02bcf86969b38f6a892b7/build/cmake/compilers.cmake#L15

**Comment by SpartanJ** [comment]
Fixed.
