### ISSUE TITLE
F5 will open new terminal tab for each run

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#327]
I have a very simple Python script that the sole purpose is to print `Hello World`. I checked `Run in terminal` in `Run`. The command for `Run` is `python3` and the argument is `${current_doc}`.

Why can't it reuse the existing terminal tab?

**Comment by SpartanJ** [comment]
Because it's a terminal shell session, ecode doesn't know what did you do with that session. Overriding your actions would be simply wrong. Btw, you can focus that session press up + enter and just rerun the last command. I won't change this behavior, sorry.
