### ISSUE TITLE
Cursor selection not selecting while hovering over minimap

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#333]
### Discussed in https://github.com/SpartanJ/ecode/discussions/332

<div type='discussions-op-text'>

<sup>Originally posted by **Curculigo** September 20, 2024</sup>
It's above text and I can't select the text hidden by it (even though I can somewhat still read the text because the Minimap is translucent).</div>

Frankly speaking, I don't want to disable the Minimap (because it's beautiful and it makes the code editor looks modern, even though I have no uses for it). It's better if you can make it possible to select the text.

**Comment by SpartanJ** [comment]
You'll have to help me to trigger this, it's a really long line? What's your font size? It's the horizontal scrollbar active? Are you using a different font than the ones that comes with ecode (DejaVu Sans Mono)? Also if you have a literal example of text that triggers the issue could be helpful.

BTW minimap can be disabled in: `Settings -› View -› Show Minimap`, same place for the scrollbars.

BTW2: I recommend you to just enable Line Wrap if you need to handle long lines, it's in `Settings -› View -› Line Wrap`.

**Comment by Curculigo** [comment]
The horizontal scrollbar should move with the mouse when I select the text. Currently, it doesn't.

**Comment by SpartanJ** [comment]
Oh, now I gotcha, [fixed](https://github.com/SpartanJ/eepp/commit/fc527d8e494889834ca66087b0a81df8f3ef9d8b).
