### ISSUE TITLE
Very minor UI improvement

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#339]
When I clear recent files and recent folders, the menu items `Recent Files` and `Recent Folders` are disabled. But the buttons `Recent Files` and `Recent Folders` on Welcome page are not. Being disabled means they are grayed out and no longer allow you to select them.

**Comment by SpartanJ** [comment]
Fixed [here](https://github.com/SpartanJ/eepp/commit/49e56f05a2918ef69227d2f8b38a86aca6accabe).
