### ISSUE TITLE
Add aarch64 support

### ISSUE THREAD

**Issue by liberodark** [SpartanJ/ecode#34]
Hi,

i want to use your software on manjaro aarch64 you can make a build for arm64 ?
Also if you can build for apple silicon too ?

Best Regards

**Comment by SpartanJ** [comment]
Yes, I want to add an aarch64 build, I need to set up the build script. It's planned. I'll take a look into it.

**Comment by SpartanJ** [comment]
I uploaded aarch64 build for 0.4.4 [here](https://github.com/SpartanJ/ecode/releases/tag/ecode-0.4.4). From now on I'll build aarch64 for every release. It should be also available in [flathub](https://github.com/flathub/flathub/pull/3898) very soon.

**Comment by liberodark** [comment]
thank you so much
