### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/ecode#344]
Does it run natively on Wayland or need XWayland? MX Linux is using X11 but I'm planning to switch to another Linux distro that will launch Wayland sessions by default. Some Linux distros even don't ship with X11 nowadays.

**Comment by SpartanJ** [comment]
It does run negatively on Wayland.

**Comment by chatchoi** [comment]
> It does run negatively on Wayland.

negatively? Do you mean natively?

**Comment by SpartanJ** [comment]
:rofl: yes, natively
