### ISSUE TITLE
Launching a new instance from an existing instance

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#346]
This idea is from another friend of mine, inspired by the open new window feature of web browsers. I think a new command in command palette is more suitable than something in the menu. I don't know any text editors have menu -> open new window like web browsers.

**Comment by SpartanJ** [comment]
Also already existing feature: `Settings -> New Window` in command pallete is called `Create New Window` (command: `create-new-window`).

**Comment by SpartanJ** [comment]
You can also open a document in a new window by right clicking a document tab and `Open in New Window...`
