### ISSUE TITLE
Can it handle shortcuts?

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/ecode#349]
I don't think so. I tried with both a folder shortcut and a file shortcut. It will open the .lnk files as text instead. This drag and drop feature is useless to me. Can I disable it?

**Comment by SpartanJ** [comment]
>  .lnk files as text instead

That's what they are, an abomination from Microsoft Windows. Use symbolic links instead.

> Can I disable it?

No. I won't do it optional, it makes no sense.

> I think shortcuts should be ignored. They are a source of security issues.

That can be done, I'll do it later.

**Comment by SpartanJ** [comment]
I ended up implementing it, it was simpler that I expected and others editors support it.
