### ISSUE TITLE
Combining "range selection" and "column selection" hang on large file

### ISSUE THREAD

**Issue by whatbh** [SpartanJ/ecode#356]
### Issue
I opened a moderately large file (1 MB), using solely "Shift selection" or "Alt selection" was smooth as usual, even when operated on the whole file. When I wanted to select a column by clicking on initial and final positions, I used <kbd>Shift</kbd>+<kbd>Alt</kbd>+<code>select</code> (i.e. combining "Shift selection" and "Alt selection"), it worked for a short range of rows (e.g. visible screen). But when I used <kbd>Shift</kbd>+<kbd>Alt</kbd>+<code>select</code> for a longer range of rows (e.g. the whole file), the program hung for a long time (that I had to terminate the process since I was not sure if it will eventually response).

One of the unique feature I love about <code>ecode</code> is its capability to quickly handle large files. This appears to be a bug. Please consider improving it.

<details>
  <summary><h3>Terminology</h3> <sup>(Click to expand)</sup>  </summary>

**Range selection** (“Shift selection”): select initial position → hold <kbd>Shift</kbd> → select final position 【function: select everything between initial and final positions】

**Column selection** (“Alt selection”): select initial position → hold <kbd>Alt</kbd> → use <kbd>Up</kbd>/<kbd>Down</kbd> key to select the same column in adjacent rows 【function: select a column across multiple rows】

**Combining “Range selection” and “Column selection”** (<kbd>Shift</kbd>+<kbd>Alt</kbd>+<code>select</code>): select initial selection → hold <kbd>Shift</kbd>+<kbd>Alt</kbd> → select final position 【function: select a column across multiple rows between initial and final positions】
</details>

OS: Windows 11
Version: ecode 0.6.3

**Comment by SpartanJ** [comment]
Hi, thanks for the report!
I can see this being tricky and problematic, since `Shift+Alt+select` and `Alt+Up/Down` do not expand the selection range but they create a new cursor for each line, if you select a whole range from a 1MB file you could be creating thousands of new cursors, I've never tried it but I would expect to find many slowdowns, I'm not sure if your specific use case could be improved much, I'll play around and try to find the most common issues (I can think a few from the top of my head), also I'm not sure if I should set an upper limit to the number of cursors that can be created (I'm pretty sure all editors do that, I just forgot to think about it), because at some point this is too heavy to handle gracefully. So in short: I'll play around and try to improve as many edge case possibles. One question: it was a plain text file or from some language? If you can specify the language it could be helpful.

> One of the unique feature I love about ecode is its capability to quickly handle large files. This appears to be a bug. Please consider improving it.

I'll do my best to improve the experience. Surprisingly currently ecode is quite fast with big files, much faster than many popular editors, so I'm happy with it, I usually open 50MB text files with word-wrap enabled and encounter zero problems, most editors struggle with that.

**Comment by SpartanJ** [comment]
I just pushed an optimization for multi-cursor that improves the performance like 100x, can you test the [nightly build](https://github.com/SpartanJ/eepp/releases/tag/nightly) and tell me if that's good enough for your case?

**Comment by whatbh** [comment]
It seems you're halfway there, detective. Joking aside, on my end, I can click on the **initial position** on a **lower line**, <kbd>Alt</kbd>+<kbd>Shift</kbd>, and then click on the **final position** on an **upper line**, then the selection works like a charm. But I can't do that if I click on an upper line first and then click on a lower line. Can you reproduce this on your end?

**Comment by whatbh** [comment]
It does not create any extra cursor except the first one at initial position, but the app does not hang. I can click on an upper line from that to create a column of cursor, but clicking on a lower line does not create anything.

**Comment by SpartanJ** [comment]
Ohh you're right, thanks! I just pushed a fix. Nightly build will be available +15m after this message.

**Comment by whatbh** [comment]
Yay. Fresh out the oven. The nightly build worked perfectly as expected. One minor thing is that, now, if I select the initial position in an upper line and click anywhere in a lower line ("Down" direction), it can create a series of cursor in single column (Figure 1). This is comfortable to have. But when I select the initial position in a lower line and then click an upper line at a different column ("Up" direction), it can end up creating multiple series of cursors (Figure 2). 

![image](https://github.com/user-attachments/assets/8589c5e4-cf18-4d9c-af0c-dcb8d2e02a0c)
Figure 1: "Down" direction. Clicking at different position still create cursors based on initial position.

![image](https://github.com/user-attachments/assets/08e36743-d3a4-4dcd-b9d2-4c4b13c190df)
Figure 2: "Up" direction. Clicking at different position create multiple series of cursors based on final position(s)

**Comment by SpartanJ** [comment]
I think that you have a point, I pushed a change that will always create new cursors in the first cursor column position. Is this what you expect? I actually don't have an strong opinion on how it should behave, so let's play around and see how it feels. vscode will generate a selection for each cursor, it tries to generate a filled rectangle of selection, I'm not sure if we should copy that behaviour, I'll think about it and also check other editors (I'm not a fan but maybe this is "standard").

Nightly should be ready in a few minutes, let me know what you think. Thanks!

**Comment by whatbh** [comment]
I should have said that I am ok with either logic for selection but I expect it to be consistent for both directions. So, I am happy with the latest nightly build. Thank you for all the hard work.

**Comment by SpartanJ** [comment]
Great! I'll keep it then. Thanks for the help!
