### ISSUE TITLE
Create new tab by (1) double click on tab bar or (2) clicking on a "+" button 

### ISSUE THREAD

**Issue by whatbh** [SpartanJ/ecode#361]
Currently, creating a new tab requires the <kbd>Ctrl</kbd>+<kbd>T</kbd> shortcut. It would be more convenient to have alternative options, such as double-clicking the tab bar or adding a "+" button next to the last tab.

**Comment by SpartanJ** [comment]
The double-click in tab bar was something I simply forgot. I just added it. I don't like buttons there so that one is discarded.

**Comment by whatbh** [comment]
Thanks! I agree, the buttons one is a matter of taste, but double click is convenient enough for me.
