### ISSUE TITLE
Borked multi cursor when writing newline with several cursors within the same line

### ISSUE THREAD

**Issue by shyperson0** [SpartanJ/ecode#364]
To reproduce, write something like this:

`delim this is a text delim this is another text delim even more text ig`

Highlight delim and Ctrl+D to highlight other instances of delim, then press enter. Instead of replacing every delim with a newline, lines after the first one are cutoff in the wrong place:

`
 this is a text d
this is another text delim even more tex
`

the second newline is one character late, and replaces one additional character, the third one comes 20 characters late.

Using Replace All in the Seach tab still works.

**Comment by SpartanJ** [comment]
Thanks for reporting it! I'm working on a fix, it will be ready soon.

**Comment by SpartanJ** [comment]
It should be fixed now, you can test it with the latest [nightly build](https://github.com/SpartanJ/eepp/releases/tag/nightly) (it will be available ~15 mins after this message). Let me know if you find anything wrong.
