### ISSUE TITLE
Highlight the current tab

### ISSUE THREAD

**Issue by chadchoi** [SpartanJ/ecode#368]
Almost impossible to tell which is the active tab if you have many files opened.

**Comment by SpartanJ** [comment]
I've no plan of changing the default contrasts of active/inactive tabs but it's very easy to customize, you can follow my comment [here](https://github.com/SpartanJ/ecode/issues/46#issuecomment-1426811663).

Active tab is the only one with a visible close button (unless you hover any tab with your mouse cursor), so I usually will just look at that, also currently focused file is on the window title.

**Comment by SpartanJ** [comment]
What I think it would be a good idea is to provide with ecode some high contrast themes by default. Which can be helpful for people with visual difficulties.
