### ISSUE TITLE
Custom tab visualisation

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#37]
I find the current tab representation a little bit hard to understand:
![image](https://user-images.githubusercontent.com/124288474/217593892-60d9ccf8-b379-4768-88d8-24342bcba430.png)

In VSCode it looks like this:
![image](https://user-images.githubusercontent.com/124288474/217593730-6d04d238-d0c1-424d-b5a7-863d0df73272.png)

It would be great if this could be customised, both the character and the spacing...

I know this is a strange request....

**Comment by SpartanJ** [comment]
I understand, I personally don't like at all how it looks in vscode, but this is a matter of taste. We can add some customization for this: custom character and alignment (left, center, right).

**Comment by SpartanJ** [comment]
Implemented, it will be available in the next release.
