### ISSUE TITLE
[Feature Request] Autoclose html tag

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#39]
Autoclose html tag after typing with >

Example:
https://github.com/formulahendry/vscode-auto-close-tag

**Comment by SpartanJ** [comment]
Auto-close XML tags already exist in the editor. It will close XML and HTML tags in documents of that type. But, I don't understand why it would close after typing <, it should be after >. Can you show me an example?
This is how it works right now:
https://user-images.githubusercontent.com/650416/217983442-c107d968-ad0c-475f-a5b5-a472c404f9a9.mp4

BTW, I'm already working on Vue support (LSP included).

**Comment by zhaolinlau** [comment]
> Auto-close XML tags already exist in the editor. It will close XML and HTML tags in documents of that type. But, I don't understand why it would close after typing <, it should be after >. 


Sorry, typo XD

**Comment by SpartanJ** [comment]
Oh haha. Then it's already there but the file extension must be .xml, .html or .htm. Vue files will support this too. What you were editing, what's your extension?
The option is enabled by default but you can check it at: (settings menu) -> Document -> Global Settings -> Auto Close Brackets & Tags -> Auto Close XML Tags.

**Comment by zhaolinlau** [comment]
> Oh haha. Then it's already there but the file extension must be .xml, .html or .htm. Vue files will support this too. What you were editing, what's your extension?
> The option is enabled by default but you can check it at: (settings menu) -> Document -> Global Settings -> Auto Close Brackets & Tags -> Auto Close XML Tags.

Oh no wonder, because I tried with blade (laravel) files and php files

**Comment by SpartanJ** [comment]
Oh, I forgot about PHP! I'll add it right away. Laravel I don't even know the extension, I'll have to check it out.
