### ISSUE TITLE
[Feature Request] Emmet support

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#40]
When i type `hello` and press `Tab` key, it will auto complete with `<hello></hello>`

emmet official website: https://emmet.io/

**Comment by SpartanJ** [comment]
It has been already [requested previously](https://github.com/SpartanJ/ecode/discussions/16). I might give it more priority if there's demand, emmet is really cool. I would love to get some collaborators for this kind of functionality.

**Comment by SpartanJ** [comment]
There seems to be possible to add emmet support by simply integrating the [emmet language server](https://github.com/olrtg/emmet-language-server). I'll try it soon, if this works I'll set the emmet LSP as the default LSP for HTML files.

**Comment by SpartanJ** [comment]
This has been added via LSP in the latest version.
