### ISSUE TITLE
[Feature Request] Auto edit html tag

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#41]
When edit the front tag, the end tag will also sync with the front tag: <`textar`></`textar`>

Example:
https://github.com/formulahendry/vscode-auto-rename-tag

**Comment by SpartanJ** [comment]
That would be cool, indeed.

**Comment by zhaolinlau** [comment]
any update?

**Comment by SpartanJ** [comment]
The feature will be available in the next release (this week).

**Comment by SpartanJ** [comment]
Released.
