### ISSUE TITLE
Search/Filter in file/folder view

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#42]
It would  be very useful to search/filter for a file in the file/folder view.

Thanks,

**Comment by SpartanJ** [comment]
The Locate tool is not enough for your usage? (Ctrl + K)

**Comment by andy0x10** [comment]
Oh thanks, I didn't know about CTRL+K.

It seems to work well :-)

But it only searches my source files... when I search for other files in the subfolder it doesn't find them.

In Unity projects sometimes you want to also search for text files with other extensions...

Anyway, this solves 95% of my needs :)

**Comment by SpartanJ** [comment]
[Here](https://github.com/SpartanJ/ecode#folder--project-settings-) is the explanation of how it works. I'll try to add a "reverse" filter per project for the next release. I mean, ecode already filters everything that it's filtered in the .gitignore, what we need is an "unfiltering" option that overwrites the gitignore.

**Comment by SpartanJ** [comment]
I'll close it, but with the commitment of adding the unfiltering option.
