### ISSUE TITLE
Retain open files and folder view when switching between folders

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#44]
If I switch from one folder to another, all the files are closed and the folder view is reset with all collapsed.

It would be fantastic if there was an option to retain the open files and also the folder view collapse state.

Thanks,

**Comment by SpartanJ** [comment]
>  also the folder view collapse state.

You're opening a subfolder of the previous folder, right?

**Comment by andy0x10** [comment]
Sorry I am mistaken - it already does what I'm asking for :)
