### ISSUE TITLE
Support for mouse wheel click-scrolling

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#47]
A lot of editors support clicking the mouse wheel and then dragging up/down to automatically smooth scroll. I've found some moments where I've missed this feature...

**Comment by SpartanJ** [comment]
The problem with this feature is that it's not universally available in other OSes, middle click mouse is a shortcut for `paste` in Linux and macOS, and I decided to copy that behavior in ecode. If I add this feature would need to be universal with other mouse gestures (may be with a modifier key pressed, for example, ctrl + middle mouse click).

**Comment by andy0x10** [comment]
True.. well it's not a big deal :)
