### ISSUE TITLE
Color picker text field changes don't persist without pressing Enter

### ISSUE THREAD

**Issue by dguenther** [SpartanJ/ecode#5]
Tested this on Windows. Moving the sliders causes the color to update immediately, and pressing Enter after changing the value in the text field causes the picker to update.

### Reproduction

1. Double-click an RGB color to open the color picker.

    ![image](https://user-images.githubusercontent.com/767083/211701984-c0da111a-f7d0-4b1d-a408-eb4eac64cf08.png)

1. Change only the color in the text field:

    ![image](https://user-images.githubusercontent.com/767083/211702171-cda01b32-d0c2-4fa4-bba0-7fbc404bd88d.png)

1. Click OK. The value from the text field doesn't replace the original text, but I'd expect it to.

**Comment by SpartanJ** [comment]
Thanks! A fix has been pushed.
