### ISSUE TITLE
[0.4.5] LSP does no longer work correctly on Linux

### ISSUE THREAD

**Issue by faliagas** [SpartanJ/ecode#50]
In the Linux version of ecode-0.4.5 the linter does not work. When hovering over a keyword nothing appears. It works OK with version 0.4.4.

**Comment by SpartanJ** [comment]
Thanks for reporting it. Can you give me a more concrete example: language, linter and LSP you're using, also a screenshot would help me, the linting could be from the a linter or the LSP diagnostics. Also, do you see the error but not the description? Is it the linter or the LSP symbol info you're referring to (since the mouse hover behavior could come from both usages).
Thanks

**Comment by faliagas** [comment]
> 

Language: C++
LSP: Both `clangd` and `ccls` are installed. I don't know which Ecode uses.
Here are some screenshots:
1) Hovering over a symbol:
- 0.4.4:
![hover-0 4 4](https://user-images.githubusercontent.com/28477635/219444456-24acb09f-c3c7-464a-862f-de28a9a91e56.png)
- 0.4.5:
![hover-0 4 5](https://user-images.githubusercontent.com/28477635/219444662-2868ef88-41df-4fe8-93d7-f7893791aaa6.png)
2) Programming error:
- 0.4.4:
![programming-error-0 4 4](https://user-images.githubusercontent.com/28477635/219444907-60a68ab0-5583-4afd-8902-6c9ba694e522.png)
- 0.4.5:
![programming-error-0 4 5](https://user-images.githubusercontent.com/28477635/219445035-472c92fe-d3c5-4ac2-91a0-734b4b3290b0.png)

**Comment by SpartanJ** [comment]
Oh, that's the LSP symbol info, it's actually broken in some situations, I sent a fix about an hour ago, let me share a build with the fix, and please tell me if it's fixed for you. Give me some minutes and I'll upload a new build in this ticket.

**Comment by SpartanJ** [comment]
Here's a build with the tentative fix, please let me know if that worked for you: [ecode-linux-0.4.5-x86_64.zip](https://github.com/SpartanJ/ecode/files/10759061/ecode-linux-0.4.5-x86_64.zip). I discovered the same issue this morning while using it, it should be the same issue.

**Comment by faliagas** [comment]
Yes, it works!

**Comment by SpartanJ** [comment]
Excellent! Thanks for testing it! I'll keep the issue open until I release a new version, given that this is a breaking issue I'll try to publish a fix this weekend.
