### ISSUE TITLE
[0.4.5] Renaming a file extension doesn't update the language icon

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#53]
![image](https://user-images.githubusercontent.com/124288474/219872905-238ca130-3e83-4b66-b506-6a0fbb981ec4.png)

Renamed the file extension from "." to ".cs" but the language icon didn't change - even after force "refresh view".

Thanks,

**Comment by SpartanJ** [comment]
Thanks for reporting it!
