### ISSUE TITLE
[0.4.6] When opening file+folder via CLI the specified file is not given focus

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#59]
For example, if I have a project with these files open:

![image](https://user-images.githubusercontent.com/124288474/220632341-dad3ce3e-25a2-4d81-b09e-83bd1d3155a6.png)

File Echo.cs has focus.

I close the project, then I open it via CLI specifying the project folder and also "BlindExpand.cs" as the file to open with row:column.  

The project will still open with Echo.cs given focus as this is the last state it was in when closed.  But the specified file should be given focus.

**Comment by SpartanJ** [comment]
Oh, I didn't notice while testing it :(, but I understand why this happens... basically, the last focus set is done by the project load, the file requested is focused first and then loads the project. I'll change the order...
