### ISSUE TITLE
Open the most recent folder on startup

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#6]
Could we have an option to toggle so the editor would open in the last opened folder automatically?
I know you can go to recent folders and open it from there, but this would make life a bit easier
I'm sorry if this is already a thing and I can't find the option

**Comment by emeraldtip** [comment]
Or does that go against the design philosophy?

**Comment by SpartanJ** [comment]
It's an absolutely reasonable request. I'll implement it as an optional behavior (I personally won't use it).

**Comment by emeraldtip** [comment]
Thanks!

**Comment by SpartanJ** [comment]
Added the option here:
![Screenshot_20230114_133525](https://user-images.githubusercontent.com/650416/212483714-a5e3a214-7afe-4afd-b81e-449a27902333.png)
It will be available in the next release.
