### ISSUE TITLE
Pyright 100% CPU Usage

### ISSUE THREAD

**Issue by PhasecoreX** [SpartanJ/ecode#64]
Hello again!

I have the same Pyright LSP config as before:
```
{
  "config": {
    ...
  },
  "keybindings": {
    ...
  },
  "servers": [
    {
      "command": "pyright-langserver --stdio",
      "file_patterns": [
        "%.py$"
      ],
      "language": "python",
      "name": "pyright",
      "url": "https://github.com/microsoft/pyright"
    }
  ]
}
```
With version 0.4.5, this works fine. With the latest 0.4.6, I see that `node /usr/bin/pyright-langserver --stdio` does start, however it makes one CPU core go to a constant 100% and doesn't mark anything in the editor.

**Comment by SpartanJ** [comment]
You're right, I made a stupid mistake in the LSP initialization. What OS are you using? I'll send you a build with the fix.

**Comment by PhasecoreX** [comment]
Thank you for the quick fix! Arch Linux, appimage, x86_64.

**Comment by SpartanJ** [comment]
No problem! Here's the new build: [ecode-linux-0.4.6-x86_64.zip](https://github.com/SpartanJ/ecode/files/10830284/ecode-linux-0.4.6-x86_64.zip)
