### ISSUE TITLE
is it possible to open ecode with empty folder?

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#66]
![image](https://user-images.githubusercontent.com/68846168/222435892-c67c9c68-f455-4a69-be55-6482b8231874.png)

**Comment by zhaolinlau** [comment]
what i want:

![image](https://user-images.githubusercontent.com/68846168/222436102-325495d2-1238-477a-af48-abddb9ce73ba.png)

**Comment by SpartanJ** [comment]
New default view:
![Screenshot_20230302_141115](https://user-images.githubusercontent.com/650416/222502230-ae1a7e4d-f645-4810-854e-b84640cb9f65.png)
I'll probably add a default view in the center to show some commands instead of opening an empty document.

**Comment by zhaolinlau** [comment]
Much appreciated!
