### ISSUE TITLE
Feature Request : Need better distinction between saved and unsaved files.

### ISSUE THREAD

**Issue by debajyoti1990** [SpartanJ/ecode#69]
Basically the title. One idea can be a pencil icon for unsaved and right icon for saved files.

**Comment by SpartanJ** [comment]
I agree. But I don't understand one thing: usually, you have only 2 states: modified and unmodified document. For unmodified documents, there's usually no indication, and for modified many editors use a different text color in the tab or an icon. The * was kinda common in old editors, I don't love it but I don't hate it either. I'm gonna explore different options and see how they look.

**Comment by debajyoti1990** [comment]
I am not very good in colour, fortunately not colour blind entirely. But many programmers I know are. 😅

**Comment by SpartanJ** [comment]
That's a really good point in favor of a very simple and clear visual indicator. An icon could also be worst than a simple * in that case. I might follow vscode and lapce in this regard. They simply change the "X" icon (close) to a circle.

**Comment by emeraldtip** [comment]
I have nothing to add other than nice issue number
