### ISSUE TITLE
Feature Request: Please add support for PowerShell terminal for windows, at least as option.

### ISSUE THREAD

**Issue by debajyoti1990** [SpartanJ/ecode#70]
PowerShell is a proper terminal, many ways better than cmd.exe. Only downside is, it is  slightly slower compared to win32 based cmd.exe as  PowerShell is built on .NET. By the way, VScode and lapce also implement PowerShell as default terminal.

**Comment by SpartanJ** [comment]
Oh, yes. It is planned. It is already supported but I wanted to be easily configurable from the editor. It's quite simple to add, I might add it for the next version. Meanwhile to use PowerShell you just need to define the SHELL global environment variable with the value "powershell.exe". ecode reads SHELL from the environment to execute it, if nothing is defined I set some for each OS by default. I already tried powershell and works just fine.

**Comment by SpartanJ** [comment]
New default shell configuration looks like (this is a Linux screenshot, you won't see powershell here hehe):
![default-shell](https://user-images.githubusercontent.com/650416/223021170-353bfe37-7aaf-4e1a-a9c5-c8571a975a8e.png)
ecode will try to locate all the commonly used shells and offer the option to select one of them, but it also let you configure any custom shell.
Windows will now default powershell.

**Comment by debajyoti1990** [comment]
I used Linux desktop in engineering school, so figured that by seeing /usr.. 😄. Can we configure custom keybinding for opening terminal in vsplit and to toggle between editor and terminal ?
