### ISSUE TITLE
Feature request. Elixir support

### ISSUE THREAD

**Issue by Wjxfi** [SpartanJ/ecode#76]
info: https://youtu.be/R7t7zca8SyM

**Comment by SpartanJ** [comment]
Elixir support has been added in the latest version (0.4.7).

**Comment by SpartanJ** [comment]
Sorry, it was already there before haha. Still pending to add the LSP support from [elixir-ls](https://github.com/elixir-lsp/elixir-ls), they don't distribute a single binary file that I can point to by default, and I don't know how to locate it automatically.

**Comment by SpartanJ** [comment]
> > Elixir support has been added in the latest version (0.4.7).
> 
> you didn't write it in readme.md

There's a support table, it's right there:
https://github.com/SpartanJ/ecode/blob/main/README.md?plain=1#L443

**Comment by SpartanJ** [comment]
That is the linter support. There's no linter support for Elixir.

**Comment by SpartanJ** [comment]
You're right!! I already fixed. Thanks!
