### ISSUE TITLE
The procedure entry point ClosePseudoConsole could not be located

### ISSUE THREAD

**Issue by PHdrr** [SpartanJ/ecode#81]
I'm running Windows 8.1 64 bit. It seems your app is for Windows 10 and above only. Could you make it work on older Windows? Thank you.

**Comment by SpartanJ** [comment]
Could you let me know if you're getting this error while starting the application or when trying to open a new terminal?
For the first case, I think I can fix it, but I won't be able to support the terminal for Windows version < 10 because the feature depends on ConPTY and it was added exactly for Windows 10 October 2018 Update (version 1809).

**Comment by PHdrr** [comment]
> Could you let me know if you're getting this error while starting the application or when trying to open a new terminal? For the first case, I think I can fix it, but I won't be able to support the terminal for Windows version < 10 because the feature depends on ConPTY and it was added exactly for Windows 10 October 2018 Update (version 1809).

I double clicked on `ecode.exe` to run it but it failed to run with this error. I didn't launch it from Windows Command Prompt.

**Comment by SpartanJ** [comment]
Great, thanks for letting me know. As far as I can remember I'm using some Windows 10 kernel functions (not only for the TTY), I'll need to check it out, I'm still not completely sure if it's worth the effort. I need to evaluate the complexity. I'll let you know if I decide to support it, and I might send you some build for testing.

**Comment by SpartanJ** [comment]
I made a few changes and the next version of ecode will start in Windows 8 but won't support terminals. I can't support them because the features required are not present in Windows 8, but at least you'll be able to use the editor.
