### ISSUE TITLE
[Plugin Request] Compiler for All Programming Languages

### ISSUE THREAD

**Issue by zhaolinlau** [SpartanJ/ecode#98]
I am here to request a plugin which allows to compile, build, and run the files/programs of C/C++, Java, Python, Lua, Rust, ..., etc. Just like how [Geany](https://www.geany.org/) did.

**Comment by SpartanJ** [comment]
There will be a very similar feature available in the next release, it's basically a generic build manager, inspired from the QtCreator build manager:

https://github.com/SpartanJ/ecode/assets/650416/67c4447a-c3ad-4fe0-b3e6-1eec89ffcf10

Geany version is much more limited, I needed something more powerful for my daily usage. It will be a core feature (no plugin).

**Comment by SpartanJ** [comment]
Thank you! Yes, this week for sure. I've been delaying this release for far too long. I need to fix a couple of minor issues with [this](https://github.com/SpartanJ/ecode/issues/41) and all will be ready.

**Comment by SpartanJ** [comment]
Released.
